<?php

/**
 * Implements hook_menu().
 */
function pdf_generator_menu()
{
    $items = [];

    $items['pdf_generator/culture'] = [
        'title' => 'Culture',
        'page callback' => 'Drupal\pdf_generator\Controller\PDFGeneratorController::generatePDFFromRenderableEntity',
        'access callback' => TRUE,
    ];

    $items['pdf_generator/dialogue'] = [
        'title' => 'Dialogue',
        'page callback' => 'Drupal\pdf_generator\Controller\PDFGeneratorController::generatePDFFromRenderableEntity',
        'access callback' => TRUE,
    ];

    $items['pdf_generator/grammar_table'] = [
        'title' => 'Grammar Table',
        'page callback' => 'Drupal\pdf_generator\Controller\PDFGeneratorController::generatePDFFromRenderableEntity',
        'access callback' => TRUE,
    ];

    $items['pdf_generator/short_story'] = [
        'title' => 'Short Story',
        'page callback' => 'Drupal\pdf_generator\Controller\PDFGeneratorController::generatePDFFromRenderableEntity',
        'access callback' => TRUE,
    ];

    return $items;
}