<?php

/**
 * Implements hook_theme().
 */
function pdf_generator_theme($existing, $type, $theme, $path)
{
  $themes = [];
  $files = Drupal::service('file_system')->scanDirectory('modules/custom', '~(?!components)([^/]+)(pdf|component).+\.(twig)~');
  foreach ($files as $file) {
    $theme_name = str_replace(['.html.twig', '-'], ['', '_'], $file->filename);

    if (str_starts_with($theme_name, 'component') || str_ends_with($theme_name, 'component')) {
      continue;
    }

    $themes[$theme_name] = [
      'path' => str_replace('/' . $file->filename, '', $file->uri),
      'variables' => [
        'entity' => NULL,
        'pdf_settings' => [
          'pdf' => FALSE,
          'show_answers' => TRUE,
          'show_translations' => TRUE,
        ],
      ],
    ];
  }

  return $themes;
}
