a4:
    orientation: portrait
    page_size: A4
    show_answers: false
    show_translations: false
    wrapper: mt-5 mx-5

landscape:
    orientation: landscape
    page_size: A4
    show_answers: false
    show_translations: false
    wrapper: m-0
